tweets: tweets_generator.c markov_chain.c linked_list.c
	gcc -Wall -Wextra -Wvla -std=c99 linked_list.c markov_chain.c tweets_generator.c -o tweets_generator
snake: snakes_and_ladders.c markov_chain.c linked_list.c
	gcc -Wall markov_chain.c linked_list.c snakes_and_ladders.c -o snakes_and_ladders
